### ISSUE TITLE
HandleStatModifier changed

### ISSUE THREAD

**Issue by cyberox** [DavidMacalaster/Solocraft#1]
Since TrinityCore commit [c69a7d1223b2ce108a221e5cc70f76cd80ae6675](https://github.com/TrinityCore/TrinityCore/commit/c69a7d1223b2ce108a221e5cc70f76cd80ae6675), Solocraft is no longer building:

`/home/trinity/TrinityCore/src/server/scripts/Custom/Solocraft/Solocraft.cpp: In member function ‘void {anonymous}::solocraft_player_instance_handler::ApplyBuffs(Player*, Map*, int, int)’:
/home/trinity/TrinityCore/src/server/scripts/Custom/Solocraft/Solocraft.cpp:76:13: error: ‘class Player’ has no member named ‘HandleStatModifier’
     player->HandleStatModifier(UnitMods(UNIT_MOD_STAT_START + i), TOTAL_PCT, float(difficulty * 100), true);`

A fix would be greatly appreciated, so I can keep using Solocraft?

**Comment by gmillerd** [comment]
@cyberox look at player->ApplyStatPctModifier for your change.
